[2023-06-19T13:17:34.628+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: time_task.create_table scheduled__2023-06-18T00:00:00+00:00 [queued]>
[2023-06-19T13:17:34.634+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: time_task.create_table scheduled__2023-06-18T00:00:00+00:00 [queued]>
[2023-06-19T13:17:34.635+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-19T13:17:34.645+0000] {taskinstance.py:1327} INFO - Executing <Task(PostgresOperator): create_table> on 2023-06-18 00:00:00+00:00
[2023-06-19T13:17:34.655+0000] {standard_task_runner.py:57} INFO - Started process 73 to run task
[2023-06-19T13:17:34.668+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'time_task', 'create_table', 'scheduled__2023-06-18T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/create_database_postgres.py', '--cfg-path', '/tmp/tmpdoxhfn7h']
[2023-06-19T13:17:34.671+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask create_table
[2023-06-19T13:17:34.731+0000] {task_command.py:410} INFO - Running <TaskInstance: time_task.create_table scheduled__2023-06-18T00:00:00+00:00 [running]> on host 747bd14dcad6
[2023-06-19T13:17:34.801+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='time_task' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2023-06-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-18T00:00:00+00:00'
[2023-06-19T13:17:34.803+0000] {sql.py:265} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS myTime (
                curr_time TIMESTAMP
            );
        
[2023-06-19T13:17:34.821+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 266, in execute
    hook = self.get_db_hook()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 181, in get_db_hook
    return self._hook
  File "/home/airflow/.local/lib/python3.7/site-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 143, in _hook
    conn = BaseHook.get_connection(self.conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 434, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres` isn't defined
[2023-06-19T13:17:34.825+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=time_task, task_id=create_table, execution_date=20230618T000000, start_date=20230619T131734, end_date=20230619T131734
[2023-06-19T13:17:34.832+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 3 for task create_table (The conn_id `postgres` isn't defined; 73)
[2023-06-19T13:17:34.874+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-19T13:17:34.893+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
